### ISSUE TITLE
Even bigger speeds ups with CUDA section doesn't work with Anaconda 4.2.0

### ISSUE THREAD

**Issue by gcapes** [harrism/numba_examples#2]
Hi, I'm trying to learn CUDA python and found this example. I'm using the latest anaconda but the last section doesn't work. I've been unable to figure out how to update it using the Continuum documentation. Would you be able to give any pointers?
Thanks

**Comment by harrism** [comment]
This should work now. I updated the notebook and [the blog post](https://devblogs.nvidia.com/parallelforall/numba-python-cuda-acceleration/) yesterday. NumbaPro is now fully open source in Numba and the libraries are in a new package called pyculib.

**Comment by gcapes** [comment]
Great, thanks! I'll give it a try.
